baseURL = "http://philibert.hugo"
DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
title = "Regis Philibert"
theme = "regisphilibert"

enableRobotsTXT = true

buildDrafts = false

# Highlights
# Set pygments ref to false to use prism
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[blackfriday]
extensions = ["hardLineBreak"]
hrefTargetBlank = true

# canonifyURLs = true
[outputs]
  section = ["html", "json", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"
  project_tag = "project_tags"

[permalinks]
  post = "blog/:year/:month/:slug/"

[params]
  description = "I'm a front end dev from Montréal specialized in Hugo and Wordpress! How can I help?"
  author = "Regis Philibert"
  jobtitle = "Front Dev in Montreal"
  twitter_handle = "regisphilibert"
  ajax = false
  env = "local"
  less = false
  sass = true
  contactFormApi = "https://api.regisphilibert.com/mail/"
  prism = false
# We use widht as key so range gets it in the right order
[params.imagesizes]
    500 = "small"
    750 = "medium"
[languages]
[languages.en]
weight = 1

[languages.fr]
weight = 2
description = "Je suis un dev front end de Montréal spécialisé dans Hugo et Wordpress! Je peux vous aider?"
jobtitle = "Dev Front à Montréal"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Defatult JPEG quality setting. Default is 75.
quality = 80