[build]
  publish = "public"
  command = "npm run stage"

[context.production.environment]
  HUGO_VERSION = "0.35"
  HUGO_ENV = "netlify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.35"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.35"